name: Release Tagger

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-previous-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Previous Tags
        shell: bash
        run: |
          git_ref="${{ github.ref }}"
          git_ref_type=$(echo "${git_ref}" | cut -d '/' -f 2)

          if [[ "${git_ref_type}" != "tags" ]]; then
            echo "Action should only run for 'tags' refs"
            exit 0
          fi

          git_ref=$(echo "${git_ref}" | cut -d '/' -f 3-)

          match="v[0-9]+.[0-9]+.[0-9]+"
          if ! [[ "${git_ref}" =~ $match ]]; then
            echo "Action should only run for tags that match the regex '$match'"
            exit 0
          fi

          major=$(echo "${git_ref}" | sed -E 's/v([0-9]*)\.([0-9]*)\.([0-9]*)/\1/')
          minor=$(echo "${git_ref}" | sed -E 's/v([0-9]*)\.([0-9]*)\.([0-9]*)/\2/')
          patch=$(echo "${git_ref}" | sed -E 's/v([0-9]*)\.([0-9]*)\.([0-9]*)/\3/')

          git tag -f "v${major}"
          git tag -f "v${major}.${minor}"

          git push --tags -f
